services:
  auth:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@db:5432/auth
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
